# Generated by Django 5.0.7 on 2024-07-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
